// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulgruttfedpnahsanwjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsZ3J1dHRmZWRwbmFoc2Fud2p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDczMzUsImV4cCI6MjA3MTE4MzMzNX0.zJchK3PjTR8JsPXaE9FYc_EAdHiNnu9FJbZMfgtDbH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});